### ISSUE TITLE
Typo and random trivia

### ISSUE THREAD

**Issue by andyatkinson** [drnic/searchcraft#2]
Hi @drnic Looks cool! Planning to try it out. Skimmed the readme and you answered one question I had: why not scenic? Sounds like you focused on a faster iteration DX. 

I noticed one typo "idation" which I think was meant to be ideation.

Random additional trivia:

Are you aware that materialized views can have indexes? I didn't see a mention of it in the readme, but you may already be aware of that and/or using indexes. 

Have you dove into the world of "incrementally maintained materialized views" which don't require a full replacement, but can receive an incremental update? 

One such open source mechanism is the pg_ivm extension.
https://github.com/sraoss/pg_ivm

A solution that brought that to Rails in some way would be amazing!

**Comment by drnic** [comment]
@andyatkinson thanks; I didn't realised I forgot to write up about indexes so I've put some docs in #3 

Unrelated, but I was in the swing of things, so #3 also starts to port over some solutions I have for text searching.

**Comment by drnic** [comment]
I personally cannot use the `pg_ivm` extension due to our constraints on our production host; but I can imagine supporting this alternate syntax `SELECT create_immv('myview', 'SELECT * FROM mytab');` instead of `CREATE MATERIALIZED VIEW myview AS SELECT * FROM mytab;`. "How hard could it be?"

Currently the wrapper SQL for the MV is at https://github.com/drnic/searchcraft/blob/2927ddb51a9eb5738a496ce9578db6b9bbddca25/lib/searchcraft/builder.rb#L101

**Comment by andyatkinson** [comment]
@drnic Makes sense on the pg_ivm extension. 

Also, re: indexes, passing on something else useful in case you didn't already know: refreshing a materialized view ideally is done "concurrently", so that other queries using it can continue to run while the results are replaced. Concurrent refreshes do require one unique index exists on the materialized view:

For here: https://github.com/drnic/searchcraft/blob/develop/lib/searchcraft/model.rb#L44

Docs on the `concurrently` keyword and unique index requirement: https://www.postgresql.org/docs/current/sql-refreshmaterializedview.html

**Comment by drnic** [comment]
Thanks, yeah I haven't yet documented how to setup concurrent refreshes; nor documented how to add a new unique index column using the sequence that's already created for you. I've created #4 to track this.

**Comment by drnic** [comment]
@andyatkinson I appreciate your comments + questions + requests for better docs. Please let me know of any other ideas you have. I definitely don't know "all things MV".
